Listagem professores
INF2-2019/aplicacao-desktop pull request #11
Opened 2019-11-12 19:52 UTC by Jonatanc05

# [Grupo 1] Listagem professores

* lista professores

## Cartões

* [Listagem de música](https://trello.com/c/poZhJ8GR/95-desktop-front-end-manipula%C3%A7%C3%A3o-dos-professores)

## Observações

Finalmente

2019-11-12 21:53 UTC, Thileps requested changes

2019-11-12 21:53 UTC, Thileps commented on app/src/java/app/diario/professores/principal/Professor.java
> +    int contador;
As variáveis são public, private ou protected?

2019-11-14 13:27 UTC, chulesnt commented
Tá commitando na master amigo

2019-11-14 14:24 UTC, closed without merging

2019-11-14 14:24 UTC, NikolasZadaTola commented
Ta incorretamente setado pra master